name: PR
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: setup npm
      run: |
        npm set @xcanchal:registry=https://npm.pkg.github.com/xcanchal
        npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

    - name: install dependencies
      run: |
        npm ci
        npx lerna bootstrap

    - name: lint
      run: npx lerna run lint